export interface ToolData {
  name: string;
  fullName: string;
  color: string;
  bgColor: string;
  borderColor: string;
  hoverShadow: string;
  description: string;
  keySkills: string[];
  proficiency?: number; // 1-5 (optional, not displayed)
  experience?: string; // (optional, not displayed)
  highlights: string[];
}

// Containers & Orchestration
export const containersTools: ToolData[] = [
  {
    name: "Docker",
    fullName: "Docker Container Platform",
    color: "from-blue-400 to-blue-600",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    hoverShadow: "rgba(37, 150, 237, 0.4)",
    description: "Leading container platform for building, shipping, and running applications",
    keySkills: ["Dockerfile", "Docker Compose", "Multi-stage builds", "Image optimization", "Container networking"],
    proficiency: 5,
    experience: "5+ years",
    highlights: [
      "Built optimized Docker images reducing size by 60%",
      "Implemented multi-stage builds for production deployments",
      "Created Docker Compose workflows for local development",
      "Managed private Docker registries and image scanning",
    ],
  },
  {
    name: "Kubernetes",
    fullName: "Kubernetes Orchestration",
    color: "from-blue-500 to-indigo-600",
    bgColor: "bg-blue-600/10",
    borderColor: "border-blue-600/30",
    hoverShadow: "rgba(50, 108, 229, 0.4)",
    description: "Production-grade container orchestration for automated deployment and scaling",
    keySkills: ["Pods & Deployments", "Services & Ingress", "ConfigMaps & Secrets", "StatefulSets", "RBAC"],
    proficiency: 5,
    experience: "4+ years",
    highlights: [
      "Managed production K8s clusters serving 10M+ requests daily",
      "Implemented auto-scaling and self-healing capabilities",
      "Designed service mesh architecture using Istio",
      "Automated cluster provisioning with Infrastructure as Code",
    ],
  },
  {
    name: "Helm",
    fullName: "Helm Package Manager",
    color: "from-indigo-400 to-indigo-700",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/30",
    hoverShadow: "rgba(15, 22, 137, 0.4)",
    description: "Kubernetes package manager for templating and deploying applications",
    keySkills: ["Chart development", "Templating", "Helm hooks", "Chart repositories", "Values files"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Created reusable Helm charts for microservices deployment",
      "Managed chart repositories and versioning strategies",
      "Implemented automated rollbacks with Helm hooks",
      "Optimized chart templating for multiple environments",
    ],
  },
  {
    name: "Docker Swarm",
    fullName: "Docker Swarm Orchestration",
    color: "from-blue-300 to-blue-500",
    bgColor: "bg-blue-400/10",
    borderColor: "border-blue-400/30",
    hoverShadow: "rgba(29, 99, 237, 0.4)",
    description: "Native Docker clustering and orchestration solution",
    keySkills: ["Swarm mode", "Services", "Stacks", "Overlay networks", "Load balancing"],
    proficiency: 3,
    experience: "2+ years",
    highlights: [
      "Deployed multi-node Swarm clusters for high availability",
      "Configured overlay networks for service discovery",
      "Implemented rolling updates and service scaling",
      "Managed secrets and config management in Swarm",
    ],
  },
  {
    name: "ECS",
    fullName: "AWS Elastic Container Service",
    color: "from-orange-400 to-orange-600",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(255, 153, 0, 0.4)",
    description: "Fully managed container orchestration service from AWS",
    keySkills: ["Task definitions", "Fargate", "EC2 launch type", "Service mesh", "Auto-scaling"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Migrated monolithic apps to ECS microservices architecture",
      "Optimized cost using Fargate Spot instances",
      "Implemented blue-green deployments with CodeDeploy",
      "Integrated ECS with ALB for traffic management",
    ],
  },
];

// CI/CD Tools
export const cicdTools: ToolData[] = [
  {
    name: "Jenkins",
    fullName: "Jenkins Automation Server",
    color: "from-red-400 to-red-700",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/30",
    hoverShadow: "rgba(211, 56, 51, 0.4)",
    description: "Leading open-source automation server for CI/CD pipelines",
    keySkills: ["Pipeline as Code", "Jenkinsfile", "Plugins", "Distributed builds", "Blue Ocean"],
    proficiency: 5,
    experience: "5+ years",
    highlights: [
      "Built complex multi-stage Jenkins pipelines for 50+ microservices",
      "Implemented distributed build system with agent pools",
      "Created shared libraries for reusable pipeline components",
      "Integrated security scanning and automated testing",
    ],
  },
  {
    name: "GitLab CI",
    fullName: "GitLab CI/CD",
    color: "from-orange-400 to-red-500",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(252, 109, 38, 0.4)",
    description: "Integrated CI/CD platform with GitLab version control",
    keySkills: [".gitlab-ci.yml", "Runners", "Pipeline stages", "Artifacts", "Environments"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Designed GitLab CI pipelines with parallel job execution",
      "Implemented auto-deploy to Kubernetes using GitLab",
      "Configured self-hosted GitLab runners for privacy",
      "Created dynamic environments for preview deployments",
    ],
  },
  {
    name: "GitHub Actions",
    fullName: "GitHub Actions Workflows",
    color: "from-blue-400 to-indigo-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    hoverShadow: "rgba(32, 136, 255, 0.4)",
    description: "GitHub-native CI/CD automation with workflow capabilities",
    keySkills: ["Workflows", "Actions", "Matrix builds", "Secrets", "Reusable workflows"],
    proficiency: 5,
    experience: "4+ years",
    highlights: [
      "Created reusable GitHub Actions for standardized deployments",
      "Implemented matrix strategy for multi-platform builds",
      "Automated release management with semantic versioning",
      "Integrated advanced security scanning with Dependabot",
    ],
  },
  {
    name: "CircleCI",
    fullName: "CircleCI Platform",
    color: "from-gray-600 to-gray-800",
    bgColor: "bg-gray-500/10",
    borderColor: "border-gray-500/30",
    hoverShadow: "rgba(52, 52, 52, 0.4)",
    description: "Cloud-based CI/CD platform with performance optimization",
    keySkills: ["config.yml", "Orbs", "Workflows", "Caching", "Docker layer caching"],
    proficiency: 4,
    experience: "2+ years",
    highlights: [
      "Optimized build times using intelligent caching strategies",
      "Implemented parallel testing to reduce CI time by 70%",
      "Created custom CircleCI orbs for team workflows",
      "Configured resource classes for compute-intensive builds",
    ],
  },
  {
    name: "ArgoCD",
    fullName: "ArgoCD GitOps",
    color: "from-orange-400 to-orange-600",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(244, 124, 72, 0.4)",
    description: "Declarative GitOps continuous delivery for Kubernetes",
    keySkills: ["GitOps workflows", "Application sync", "Auto-sync", "Helm integration", "Multi-cluster"],
    proficiency: 4,
    experience: "2+ years",
    highlights: [
      "Implemented GitOps workflows for automated K8s deployments",
      "Managed multi-cluster deployments with ArgoCD ApplicationSets",
      "Configured automated sync policies and health checks",
      "Integrated ArgoCD with image updater for automatic promotions",
    ],
  },
];

// Infrastructure as Code
export const iacTools: ToolData[] = [
  {
    name: "Terraform",
    fullName: "HashiCorp Terraform",
    color: "from-purple-400 to-purple-700",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/30",
    hoverShadow: "rgba(92, 78, 229, 0.4)",
    description: "Infrastructure as Code tool for cloud provisioning and management",
    keySkills: ["HCL syntax", "Modules", "State management", "Providers", "Workspaces"],
    proficiency: 5,
    experience: "5+ years",
    highlights: [
      "Provisioned multi-cloud infrastructure for 100+ services",
      "Created reusable Terraform modules for standardized deployments",
      "Implemented remote state management with locking",
      "Automated infrastructure testing with Terratest",
    ],
  },
  {
    name: "Ansible",
    fullName: "Ansible Automation",
    color: "from-red-500 to-black",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/30",
    hoverShadow: "rgba(0, 0, 0, 0.4)",
    description: "Agentless automation tool for configuration management",
    keySkills: ["Playbooks", "Roles", "Inventory", "Modules", "Vault"],
    proficiency: 4,
    experience: "4+ years",
    highlights: [
      "Automated server configuration for 500+ nodes",
      "Created Ansible roles for consistent environment setup",
      "Implemented Ansible Vault for secrets management",
      "Integrated Ansible with CI/CD for deployment automation",
    ],
  },
  {
    name: "CloudFormation",
    fullName: "AWS CloudFormation",
    color: "from-green-500 to-green-700",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/30",
    hoverShadow: "rgba(46, 125, 50, 0.4)",
    description: "AWS native infrastructure as code service",
    keySkills: ["Templates", "Stacks", "StackSets", "Change sets", "Nested stacks"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Designed CloudFormation templates for AWS infrastructure",
      "Implemented cross-region deployments with StackSets",
      "Created modular templates using nested stacks",
      "Automated rollback strategies with change sets",
    ],
  },
  {
    name: "Pulumi",
    fullName: "Pulumi Infrastructure SDK",
    color: "from-yellow-400 to-purple-500",
    bgColor: "bg-yellow-500/10",
    borderColor: "border-purple-500/30",
    hoverShadow: "rgba(126, 87, 194, 0.4)",
    description: "Modern infrastructure as code using programming languages",
    keySkills: ["TypeScript/Python", "Component resources", "Stack outputs", "Secrets", "Policy as Code"],
    proficiency: 3,
    experience: "1+ years",
    highlights: [
      "Migrated Terraform configs to Pulumi for better type safety",
      "Built custom component resources for complex infrastructure",
      "Implemented Policy as Code with Pulumi CrossGuard",
      "Leveraged programming language features for dynamic infrastructure",
    ],
  },
  {
    name: "Chef",
    fullName: "Chef Configuration Management",
    color: "from-orange-400 to-orange-700",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(248, 104, 37, 0.4)",
    description: "Configuration management tool for infrastructure automation",
    keySkills: ["Cookbooks", "Recipes", "Resources", "Chef Server", "Test Kitchen"],
    proficiency: 3,
    experience: "2+ years",
    highlights: [
      "Developed Chef cookbooks for application deployment",
      "Managed Chef Server infrastructure for multiple teams",
      "Implemented automated testing with Test Kitchen",
      "Created custom Chef resources for specialized tasks",
    ],
  },
];

// Monitoring & Logging
export const monitoringTools: ToolData[] = [
  {
    name: "Prometheus",
    fullName: "Prometheus Monitoring",
    color: "from-orange-400 to-red-500",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(230, 82, 44, 0.4)",
    description: "Open-source monitoring and alerting toolkit with time-series database",
    keySkills: ["PromQL", "Metrics collection", "Alertmanager", "Service discovery", "Exporters"],
    proficiency: 5,
    experience: "4+ years",
    highlights: [
      "Designed Prometheus monitoring for Kubernetes clusters",
      "Created custom exporters for application metrics",
      "Implemented advanced PromQL queries for SLO tracking",
      "Configured Alertmanager for intelligent alert routing",
    ],
  },
  {
    name: "Grafana",
    fullName: "Grafana Visualization",
    color: "from-orange-400 to-yellow-500",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    hoverShadow: "rgba(244, 104, 0, 0.4)",
    description: "Analytics and monitoring platform with beautiful dashboards",
    keySkills: ["Dashboard creation", "Templating", "Alerts", "Plugins", "Data sources"],
    proficiency: 5,
    experience: "4+ years",
    highlights: [
      "Built 50+ Grafana dashboards for infrastructure monitoring",
      "Implemented dynamic dashboards with template variables",
      "Created custom panels and plugins for specific metrics",
      "Configured unified alerting across multiple data sources",
    ],
  },
  {
    name: "ELK Stack",
    fullName: "Elasticsearch, Logstash, Kibana",
    color: "from-teal-400 via-cyan-400 to-yellow-500",
    bgColor: "bg-teal-500/10",
    borderColor: "border-teal-500/30",
    hoverShadow: "rgba(0, 191, 179, 0.4)",
    description: "Complete log aggregation, search, and visualization platform",
    keySkills: ["Elasticsearch", "Logstash pipelines", "Kibana", "Index management", "Query DSL"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Processed 100GB+ daily logs with optimized Logstash pipelines",
      "Designed Elasticsearch cluster for high-availability logging",
      "Created Kibana visualizations for log analysis and troubleshooting",
      "Implemented index lifecycle management for cost optimization",
    ],
  },
  {
    name: "Datadog",
    fullName: "Datadog Monitoring Platform",
    color: "from-purple-500 to-purple-700",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/30",
    hoverShadow: "rgba(99, 44, 166, 0.4)",
    description: "Cloud-scale monitoring and analytics platform",
    keySkills: ["APM", "Log management", "Metrics", "Dashboards", "Integrations"],
    proficiency: 4,
    experience: "2+ years",
    highlights: [
      "Implemented full-stack observability with Datadog APM",
      "Created custom metrics and monitors for SLO tracking",
      "Integrated 30+ services with Datadog for unified monitoring",
      "Built automated incident response workflows",
    ],
  },
  {
    name: "New Relic",
    fullName: "New Relic Observability",
    color: "from-teal-400 to-teal-600",
    bgColor: "bg-teal-500/10",
    borderColor: "border-teal-500/30",
    hoverShadow: "rgba(0, 140, 153, 0.4)",
    description: "Full-stack observability platform for modern applications",
    keySkills: ["APM", "Browser monitoring", "Infrastructure", "Synthetics", "NRQL"],
    proficiency: 3,
    experience: "2+ years",
    highlights: [
      "Deployed New Relic APM for application performance monitoring",
      "Implemented synthetic monitoring for proactive alerting",
      "Created custom NRQL queries for advanced analytics",
      "Integrated New Relic with incident management tools",
    ],
  },
];

// Security & Compliance
export const securityTools: ToolData[] = [
  {
    name: "HashiCorp Vault",
    fullName: "HashiCorp Vault",
    color: "from-yellow-400 to-black",
    bgColor: "bg-yellow-500/10",
    borderColor: "border-yellow-500/30",
    hoverShadow: "rgba(255, 180, 0, 0.4)",
    description: "Secrets management and data protection platform",
    keySkills: ["Secrets engines", "Authentication", "PKI", "Encryption", "Dynamic secrets"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Implemented centralized secrets management with Vault",
      "Configured dynamic database credentials for enhanced security",
      "Deployed Vault in HA mode for high availability",
      "Integrated Vault with Kubernetes for pod authentication",
    ],
  },
  {
    name: "SonarQube",
    fullName: "SonarQube Code Quality",
    color: "from-blue-400 to-blue-600",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    hoverShadow: "rgba(78, 155, 216, 0.4)",
    description: "Continuous code quality and security inspection platform",
    keySkills: ["Code analysis", "Quality gates", "Security hotspots", "Technical debt", "Custom rules"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Integrated SonarQube into CI/CD for automated code quality checks",
      "Configured custom quality gates for project requirements",
      "Reduced technical debt by 40% through proactive code analysis",
      "Implemented security scanning for vulnerability detection",
    ],
  },
  {
    name: "Snyk",
    fullName: "Snyk Security Platform",
    color: "from-purple-500 to-purple-800",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/30",
    hoverShadow: "rgba(76, 60, 141, 0.4)",
    description: "Developer-first security platform for finding and fixing vulnerabilities",
    keySkills: ["Dependency scanning", "Container scanning", "IaC security", "License compliance", "Fix PRs"],
    proficiency: 4,
    experience: "2+ years",
    highlights: [
      "Automated vulnerability scanning in CI/CD pipelines",
      "Implemented container image scanning with Snyk",
      "Configured IaC security scanning for Terraform and K8s",
      "Reduced critical vulnerabilities by 80% with automated fixes",
    ],
  },
  {
    name: "OWASP",
    fullName: "OWASP Security Standards",
    color: "from-blue-400 to-blue-600",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    hoverShadow: "rgba(30, 144, 255, 0.4)",
    description: "Industry-standard security practices and tools",
    keySkills: ["ZAP scanner", "Dependency-Check", "Top 10", "Security testing", "Threat modeling"],
    proficiency: 4,
    experience: "3+ years",
    highlights: [
      "Implemented OWASP Top 10 security controls",
      "Automated security testing with OWASP ZAP",
      "Performed dependency vulnerability scanning",
      "Conducted security training based on OWASP guidelines",
    ],
  },
  {
    name: "SSL/TLS",
    fullName: "SSL/TLS Certificate Management",
    color: "from-blue-400 to-cyan-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    hoverShadow: "rgba(74, 168, 255, 0.4)",
    description: "Secure communication protocols and certificate management",
    keySkills: ["Certificate management", "Let's Encrypt", "cert-manager", "HTTPS", "mTLS"],
    proficiency: 5,
    experience: "5+ years",
    highlights: [
      "Automated certificate renewal with cert-manager in Kubernetes",
      "Implemented mTLS for service-to-service communication",
      "Configured Let's Encrypt for free SSL certificates",
      "Managed PKI infrastructure for internal services",
    ],
  },
];